### PR TITLE
Support for progressive encoding for JPEG files. Fix builds

### PR DESCRIPTION
**Pull request by octplane**
This commits contains 2 things:
- A fix to make the gem build correctly on Master
- A new progressive support feature on #each(progressive = true) to generate progressive encoded images.

### CODE REVIEW

**Comment by ender672** [comment]
Thanks for the pull request! I'll take a look at this today.

**Comment by octplane** [comment]
Hum,

61390ba is actually WIP, although I actually need the feature somewhere. I thought some extra flags could be passed when reading an Image to select which marker to keep. ICC is an important one because it alters the render depending on the physical screen...

**Comment by ender672** [comment]
Can you separate out the gem build fixes from the rest? I could apply those right away.

Why the version bump?

I like the idea of preserving ICC profiles when they exist in the original JPEG. No questions need to be asked -- if the original had one, then the resized image might as well have one too.

You notice that it is difficult to pass the ICC information through the image transformation pipeline. The transformation functions shouldn't have to care about such details. What if jpeg.c exposed a method that gives you the ICC header?

What are you using progressive JPEG for?

**Comment by octplane** [comment]
Hi,

I'll fix the diff to separate the gem build fixes from the rest (not sure how i'm going to do that with git though). This might get messy :-)

If jpeg.c exposed a method to get the ICC, there should also be a method to re-add it when serializing the image using #each.

We're using progressive JPEG because progressive compression is usually a bit better than regular compression and we are looking for way to make the images as small as possible.

**Comment by octplane** [comment]
I've created another pull request with only the build fixes.

I'll work on adding the get_icc method on jpeg.c but I need your input as how to make this a parameter of each (hash table such as { progressive: true, icc: my_icc_tag } ?

Oh and the version bump is needed because it should allow to push the new gem to rubygems and update all my applications with the new features :)

Cheers,
Pierre.

**Pull request closed without merging**
